version: '3.4'
services:
  mfence:
    image: mfence:try1
    ports:
      - '127.0.0.1:6565:80'
    volumes:
      - logs-folder:/var/log/nginx/
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    command: "-nginx.scrape-uri http://mfence:80/nginx_status"
    ports:
      - '127.0.0.1:9113:9113'
    links:
      - mfence 
    depends_on:
      - mfence
  uwsgi-exporter:
    image: timonwong/uwsgi-exporter:v1.0.0
    command: "--stats.uri http://mfence/uwsgi_status"
    ports:
      - '127.0.0.1:9117:9117'
    links:
      - mfence
    depends_on:
      - mfence
  nginx-logs-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1.7.1
    command: "mnt/nginxlogs/access_not_json.log"
    ports:
      - '127.0.0.1:4040:4040'
    volumes:
      - logs-folder:/mnt/nginxlogs/
    links:
      - mfence
    depends_on:
      - mfence
  prometheus:
    image: prom/prometheus:v2.19.3
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--log.level=debug"]
    ports:
      - '127.0.0.1:9090:9090'
    volumes:
      - type: bind
        source: ${PWD}/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    links:
      - mfence
      - nginx-prometheus-exporter
      - uwsgi-exporter
      - nginx-logs-exporter
    depends_on:
      - mfence
volumes:
  logs-folder:
